### ISSUE TITLE
Functions in Go don't return interfaces

### ISSUE THREAD

**Issue by ihippik** [greazleay/vehicle-api#10]
Functions in Go don't return interfaces, only concrete structures.
But functions can take interfaces as arguments.

we need low coupling - this is the main reason.

```
func NewVehicleController() VehicleController {
	return &vehicleController{
		vehicleService: services.NewVehicleService(config.DB),
	}
}
```

**Comment by greazleay** [comment]
Made modifications, affected functions are returning structs instead
