### ISSUE TITLE
Main function

### ISSUE THREAD

**Issue by ihippik** [greazleay/vehicle-api#3]
I found two main functions here.
So, better not to do that. We have another two approaches:

- make two directories in `cmd` folder and each has its own main package and its own main function
-  use cli library with two different commands like this https://github.com/urfave/cli

**Comment by greazleay** [comment]
I am not able to find a second main function. There is one main function in the main.go entry file which has an init function for some setups like loading environment variables and connecting to the database before the main function is invoked.

The other main function I could think of is the TestMain function which is used to setup test suites

**Comment by greazleay** [comment]
Apologies, I found it in the file for running migrations. Would make adjustments
