### ISSUE TITLE
Reduce variable scope

### ISSUE THREAD

**Issue by ihippik** [greazleay/vehicle-api#8]
```
	err := godotenv.Load()

	if err != nil {
		log.Fatal("Error loading .env file")
	}
```

you can make it like this

```
	if err := godotenv.Load(); err != nil {
		log.Fatal("Error loading .env file")
	}
```

if func returns just err it should look good. And few advantages:
1. shorter
2. reduce scope - solve problems with shadowing and any tricky bugs

**Comment by greazleay** [comment]
Suggested changes made
